#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT="$ROOT"
if [ ! -d "$PROJECT_ROOT/k8s" ]; then PROJECT_ROOT=$(CDPATH= cd -- "$ROOT/../.." && pwd); fi
NAMESPACE=${NAMESPACE:-netmark}
CLUSTER_NAME=${CLUSTER_NAME:-netmark}
MANIFEST="$PROJECT_ROOT/k8s/postgres.yaml"
APP_MANIFEST="$PROJECT_ROOT/k8s/netmark.yaml"
POSTGRES_USER=${POSTGRES_USER:-netmark}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
POSTGRES_DB=${POSTGRES_DB:-netmark}
ENV_FILE=${NETMARK_POSTGRES_ENV:-$PROJECT_ROOT/postgres.env}
CONFIG="$ROOT/netmark.config"

if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

if ! command -v kubectl >/dev/null 2>&1; then
  echo "kubectl is required" >&2
  exit 1
fi

docker build -t netmark-tools:local -f "$PROJECT_ROOT/k8s/Dockerfile" "$PROJECT_ROOT/k8s"
docker build -t netmark-app:local -f "$PROJECT_ROOT/k8s/Dockerfile.netmark" "$PROJECT_ROOT"

if ! kubectl cluster-info >/dev/null 2>&1; then
  if command -v kind >/dev/null 2>&1; then
    if ! kind get clusters | grep -qx "$CLUSTER_NAME"; then
      kind create cluster --name "$CLUSTER_NAME" --config "$PROJECT_ROOT/k8s/kind-config.yaml"
    fi
    kubectl config use-context "kind-$CLUSTER_NAME" >/dev/null
  else
    echo "No Kubernetes cluster is reachable. Enable Docker Desktop Kubernetes or install kind, then rerun init.sh." >&2
    exit 1
  fi
fi

if [ -n "${POSTGRES_USER:-}" ] && [ -n "${POSTGRES_PASSWORD:-}" ] && [ -n "${POSTGRES_DB:-}" ]; then
  # Ensure config generation works when postgres.env is absent by using manifest defaults
  kubectl -n "$NAMESPACE" create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  kubectl -n "$NAMESPACE" create secret generic netmark-postgres \
    --from-literal=POSTGRES_USER="$POSTGRES_USER" \
    --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
    --from-literal=POSTGRES_DB="$POSTGRES_DB" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
fi

kubectl apply -f "$MANIFEST"
kubectl -n "$NAMESPACE" rollout status deployment/netmark-postgres --timeout=180s

# The app image is local, so hand it to the kind nodes when kind is in use.
if command -v kind >/dev/null 2>&1 && kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
  kind load docker-image netmark-app:local --name "$CLUSTER_NAME"
fi
kubectl apply -f "$APP_MANIFEST"
kubectl -n "$NAMESPACE" rollout status deployment/netmark-app --timeout=180s

kubectl -n "$NAMESPACE" port-forward service/netmark-postgres 5433:5432 >/tmp/netmark-postgres-port-forward.log 2>&1 &
FORWARD_PID=$!
trap 'kill "$FORWARD_PID" 2>/dev/null || true' EXIT

cat > "$CONFIG" <<EOF
# Generated by init.sh. Override with: configure metrics <connection>
metrics:
  sql: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5433/${POSTGRES_DB}"
EOF
echo "PostgreSQL/Timescale is ready on 127.0.0.1:5433"
echo "netmark web interface (web CLI): http://127.0.0.1:8080"
echo "Host CLI: $PROJECT_ROOT/netmarkctl help"
echo "Config written to $CONFIG"
echo "Use: metrics enable"
wait "$FORWARD_PID"
